#pragma once

#define MAT_FLAGS_NONE 0
#define MAT_FLAGS_SKY 0x4      // SURF_DRAWSKY
#define MAT_FLAGS_LAVA 0x400   // SURF_DRAWLAVA
#define MAT_FLAGS_SLIME 0x800  // SURF_DRAWSLIME
#define MAT_FLAGS_TELE 0x1000  // SURF_DRAWTELE
#define MAT_FLAGS_WATER 0x2000 // SURF_DRAWWATER
#define MAT_FLAGS_WATERFALL 0x4000
#define MAT_FLAGS_SPRITE 0x8000
// material has a solid color. n0 is albedo, n1 is emission (tex can still be used for alpha)
#define MAT_FLAGS_SOLID 0x1
